name: vSR Environment
values:
  - key: api_base_url
    value: 'http://semantic-router-api-vllm-semantic-router-system.apps.cluster-XXXXX.XXXXX.sandbox0000.opentlc.com'
    enabled: true
  - key: envoy_base_url
    value: 'http://envoy-http-vllm-semantic-router-system.apps.cluster-XXXXX.XXXXX.sandbox0000.opentlc.com'
    enabled: true
  - key: metrics_base_url
    value: 'http://semantic-router-metrics-vllm-semantic-router-system.apps.cluster-XXXXX.XXXXX.sandbox0000.opentlc.com'
    enabled: true
  - key: routing_api_base_url
    value: 'http://localhost:8082'
    enabled: true
